whitelist-enabled: true

messages:
  clear-message: 'Все игроки были удалены из белого списка'
  remove-message: 'Игрок был удален с белого списка'
  add-message: 'Игрок был добавлен в белый список'

  remove-subcommand-help: 'Используйте: /whitelist remove <ник>'
  add-subcommand-help: 'Используйте: /whitelist add <ник>'

  kick-message: 'Вы не в вайтлисте.'

players: []